### ISSUE TITLE
Fails on hashes that start with a "0"

### ISSUE THREAD

**Issue by andrewchilds** [Raynes/clavatar#4]
Some hashes end up with a "0" at the beginning of the string, which gets cut off, causing an invalid URL.

``` clj
clavatar.core=> (.toString (BigInteger. 1 (.digest digest (.getBytes bad-email "UTF-8"))) 16)
"d0b93c271623136e1ab5d9af4f849e5"
clavatar.core=> (.toString (BigInteger. 1 (.digest digest (.getBytes good-email "UTF-8"))) 16)
"5f6a67aef4850dfae973fd7200c6baac"
```

Notice that the first hash is 31 characters long vs. the usual 32. I wish I could supply a specific email address you could test against, but I can't share customer data.

Cheers,
Andrew

**Comment by Raynes** [comment]
Yeah, this algorithm is silly. I'll fix this asap.

**Comment by Raynes** [comment]
0.3.0 ought to fix this issue

**Comment by andrewchilds** [comment]
I've verified that 0.3.0 corrects this issue. Thanks! :beers:
